name: LinearAlgebraForCAP
version: 2015.11.05
date: 05/11/2015
description: Category of Matrices over a Field for CAP

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "MatricesForHomalg"
      version: ">= 2015.06.20"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "CAP"
      version: ">= 2015.08.17"
      url: "http://homalg-project.github.io/CAP_project/CAP/"
    - name: "ToolsForHomalg"
      version: ">=2015.09.18"
      url: "http://homalg-project.github.io/homalg_project/ToolsForHomalg/"

www: http://homalg-project.github.io/CAP_project/LinearAlgebraForCAP/
readme: http://homalg-project.github.io/CAP_project/LinearAlgebraForCAP/README
packageinfo: http://homalg-project.github.io/CAP_project/LinearAlgebraForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CAP_project/releases/download/LinearAlgebraForCAP-2015.11.05/LinearAlgebraForCAP-2015.11.05.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/CAP_project/releases/download/LinearAlgebraForCAP-2015.11.05/LinearAlgebraForCAP-2015.11.05.zip

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
