name: GeneralizedMorphismsForCAP
version: 2015.11.05
date: 05/11/2015
description: Implementations of generalized morphisms for the CAP project

authors:
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

maintainers:
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">=2015.05.08"
      url: "http://homalg-project.github.io/CAP_project/CAP/"

www: http://homalg-project.github.io/CAP_project/GeneralizedMorphismsForCAP/
readme: http://homalg-project.github.io/CAP_project/GeneralizedMorphismsForCAP/README
packageinfo: http://homalg-project.github.io/CAP_project/GeneralizedMorphismsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CAP_project/releases/download/GeneralizedMorphismsForCAP-2015.11.05/GeneralizedMorphismsForCAP-2015.11.05.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/CAP_project/releases/download/GeneralizedMorphismsForCAP-2015.11.05/GeneralizedMorphismsForCAP-2015.11.05.zip

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
